[build]
command = "ng build --configuration=production"
publish = "dist/news-project"


[[redirects]]
from = "/api/*"
to = "/.netlify/functions/fetchNews/:splat"
status = 200


[functions]
directory = "netlify/functions"